# Generated by Django 3.2.3 on 2022-01-16 04:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basic_api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='drfpost',
            name='author',
        ),
        migrations.RemoveField(
            model_name='drfpost',
            name='rating',
        ),
        migrations.AddField(
            model_name='drfpost',
            name='file',
            field=models.FileField(default=1, upload_to='documents/%Y/%m/%d'),
            preserve_default=False,
        ),
    ]
